# Generated by Django 4.0 on 2021-12-22 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Имя категориии')),
                ('description', models.TextField(verbose_name='Описание')),
                ('slug', models.SlugField(max_length=160, unique=True)),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок статьи')),
                ('img', models.ImageField(upload_to='images/', verbose_name='Картинка поста')),
                ('content', models.TextField(verbose_name='Описание')),
                ('date', models.DateField(auto_now=True, verbose_name='Дата публикации')),
                ('slug', models.SlugField(max_length=160, unique=True)),
                ('posted', models.BooleanField(default=False, verbose_name='Опубликованно')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='news.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Пост',
                'verbose_name_plural': 'Посты',
            },
        ),
    ]
