# Generated by Django 4.0 on 2022-01-07 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_navbar_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navbar',
            name='position',
            field=models.IntegerField(default=0, verbose_name='Позиция'),
        ),
    ]
